import { useState } from 'react';
import { CatalogDisc } from '../../types/catalog/Disc.type';
import { ImageFile, VideoFile } from '@/types/catalog/Common.type';
import CatalogService from '../../service/catalog/CatalogService';

const useAddDisc = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const addDisc = async (
    title: string,
    videoFiles: VideoFile[],
    imageFiles: ImageFile[],
    isPartOfSet: boolean,
    isRentalDisc: boolean,
    containsSpecialFeatures: boolean,
    resourceId?: string,
    releaseDate?: string,
    genre?: string,
    language?: string,
    subtitles?: string[],
    regionCode?: string
  ) => {
    setLoading(true);
    setError(null);

    try {
      const disc: CatalogDisc = {
        id: '', // ID generated by the backend
        title,
        videoFiles,
        imageFiles,
        isPartOfSet,
        isRentalDisc,
        containsSpecialFeatures,
        mediaId: resourceId,
        releaseDate,
        language,
        subtitles,
        regionCode,
      };

      const service = new CatalogService('discs');
      await service.addDocument(disc);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return { addDisc, loading, error };
};

export default useAddDisc;