// The Actor interface represents an actor in the database
// It includes the actor's ID, full name, associated movie and series IDs, birthplace, birthday, and notes
// This dhould be used for all operations except for the initial entry of an actor in the form
export interface Actor {
  id: string; // Unique string, 20 alphanumeric characters
  fullName: string; // Full name of the actor
  movieIds: string[]; // List of movie IDs the actor is associated with
  seriesIds: string[]; // List of series IDs the actor is associated with
  birthplace: string; // Birthplace of the actor
  birthday: string; // Birthday of the actor
  notes: string; // Additional notes about the actor
}

// This interface is used for the initial entry of an actor in the form
// It is similar to the Actor interface but does not include the id field
// as it will be generated by the Firestore service when the document is created
export interface ActorInitialEntry {
    fullName: string; // Full name of the actor
    movieIds: string[]; // List of movie IDs the actor is associated with
    seriesIds: string[]; // List of series IDs the actor is associated with
    birthplace: string; // Birthplace of the actor
    birthday: string; // Birthday of the actor
    notes: string; // Additional notes about the actor
}