import { OmdbResponseFull } from "@/types/OmdbResponse.type";

export const sampleOmdbResponseData: OmdbResponseFull = {
    title: 'Inception',
    year: '2010',
    rated: 'PG-13',
    released: '16 Jul 2010',
    runtime: '148 min',
    genre: 'Action, Adventure, Sci-Fi',
    director: 'Christopher Nolan',
    writer: 'Christopher Nolan',
    actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
    plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    language: 'English, Japanese, French',
    country: 'USA, UK',
    awards: 'Won 4 Oscars. Another 152 wins & 204 nominations.',
    poster: 'https://m.media-amazon.com/images/I/51s+5c5bYFL._AC_.jpg',
    ratings: [],
    metascore: '74',
    imdbRating: '8.8',
    imdbVotes: '2,074,000',
    imdbID: 'tt1375666',
    type: 'movie',
    dvd: '07 Dec 2010',
    boxOffice: '$292,576,195',
    production: 'Warner Bros. Pictures',
    website: 'http://inceptionmovie.warnerbros.com/',
    response: 'True',
  };