import { OmdbResponseFull } from "@/types/OmdbResponse.type";

export const sampleOmdbResponseData: OmdbResponseFull = {
    Title: 'Inception',
    Year: '2010',
    Rated: 'PG-13',
    Released: '16 Jul 2010',
    Runtime: '148 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Christopher Nolan',
    Writer: 'Christopher Nolan',
    Actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
    Plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    Language: 'English, Japanese, French',
    Country: 'USA, UK',
    Awards: 'Won 4 Oscars. Another 152 wins & 204 nominations.',
    Poster: 'https://m.media-amazon.com/images/I/51s+5c5bYFL._AC_.jpg',
    Ratings: [],
    Metascore: '74',
    imdbRating: '8.8',
    imdbVotes: '2,074,000',
    imdbID: 'tt1375666',
    Type: 'movie',
    Dvd: '07 Dec 2010',
    BoxOffice: '$292,576,195',
    Production: 'Warner Bros. Pictures',
    Website: 'http://inceptionmovie.warnerbros.com/',
    Response: 'True',
  };