"""add_tape_id_to_session_files

Revision ID: 21bea9fa707c
Revises: ba30c3f2ef19
Create Date: 2026-05-30 17:20:01.754754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bea9fa707c'
down_revision: Union[str, None] = 'ba30c3f2ef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tape_session_files', sa.Column('tape_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tape_session_files_tape_id'), 'tape_session_files', ['tape_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tape_session_files_tape_id'), table_name='tape_session_files')
    op.drop_column('tape_session_files', 'tape_id')
    # ### end Alembic commands ###
