"""baseline

Revision ID: fe53871a3993
Revises: 
Create Date: 2026-05-30 13:57:33.655530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe53871a3993'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingress_processing_history', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('ingress_queue', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('jellyfin_folders', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('library_paths', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('media_assignments', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('media_files', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('media_matches', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('scan_results', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('scanned_directories', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    op.alter_column('scanned_files', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scanned_files', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('scanned_directories', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('scan_results', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('media_matches', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('media_files', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('media_assignments', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('library_paths', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('jellyfin_folders', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('ingress_queue', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('ingress_processing_history', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    # ### end Alembic commands ###
